apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    name: backend
    release: prometheus
  name: backend
  namespace: observability
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ligenchang/observability-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  name: backend-service
  labels:
    app: backend
  namespace: observability
spec:
  selector:
    app: backend
  ports:
    - name: backend
      port: 8081
      targetPort: 8080
  type: LoadBalancer

