apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    name: backend
    release: prometheus
  name: backend
  namespace: observability
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ligenchang/observability-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
